IF NOT EXISTS (SELECT TOP 1 1 FROM CountryRegion)
BEGIN
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AD', N'Andorra')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AE', N'United Arab Emirates')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AF', N'Afghanistan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AG', N'Antigua and Barbuda')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AI', N'Anguilla')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AL', N'Albania')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AM', N'Armenia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AN', N'Netherlands Antilles')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AO', N'Anla')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AQ', N'Antarctica')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AR', N'Argentina')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AS', N'American Samoa')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AT', N'Austria')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AU', N'Australia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AW', N'Aruba')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'AZ', N'Azerbaijan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BA', N'Bosnia and Herzevina')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BB', N'Barbados')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BD', N'Bangladesh')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BE', N'Belgium')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BF', N'Burkina Faso')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BG', N'Bulgaria')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BH', N'Bahrain')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BI', N'Burundi')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BJ', N'Benin')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BM', N'Bermuda')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BN', N'Brunei')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BO', N'Bolivia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BR', N'Brazil')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BS', N'Bahamas, The')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BT', N'Bhutan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BV', N'Bouvet Island')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BW', N'Botswana')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BY', N'Belarus')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'BZ', N'Belize')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CA', N'Canada')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CC', N'Cocos (Keeling) Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CD', N'Con (DRC)')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CF', N'Central African Republic')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CG', N'Con')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CH', N'Switzerland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CI', N'Côte d''Ivoire')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CK', N'Cook Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CL', N'Chile')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CM', N'Cameroon')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CN', N'China')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CO', N'Colombia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CR', N'Costa Rica')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CS', N'Serbia and Montenegro')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CU', N'Cuba')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CV', N'Cape Verde')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CX', N'Christmas Island')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CY', N'Cyprus')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'CZ', N'Czech Republic')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'DE', N'Germany')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'DJ', N'Djibouti')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'DK', N'Denmark')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'DM', N'Dominica')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'DO', N'Dominican Republic')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'DZ', N'Algeria')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'EC', N'Ecuador')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'EE', N'Estonia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'EG', N'Egypt')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ER', N'Eritrea')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ES', N'Spain')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ET', N'Ethiopia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'FI', N'Finland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'FJ', N'Fiji Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'FK', N'Falkland Islands (Islas Malvinas)')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'FM', N'Micronesia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'FO', N'Faroe Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'FR', N'France')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GA', N'Gabon')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GB', N'United Kingdom')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GD', N'Grenada')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GE', N'Georgia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GF', N'French Guiana')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GH', N'Ghana')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GI', N'Gibraltar')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GL', N'Greenland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GM', N'Gambia, The')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GN', N'Guinea')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GP', N'Guadeloupe')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GQ', N'Equatorial Guinea')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GR', N'Greece')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GS', N'South Georgia and the South Sandwich Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GT', N'Guatemala')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GU', N'Guam')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GW', N'Guinea-Bissau')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'GY', N'Guyana')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'HK', N'Hong Kong SAR')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'HM', N'Heard Island and McDonald Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'HN', N'Honduras')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'HR', N'Croatia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'HT', N'Haiti')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'HU', N'Hungary')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ID', N'Indonesia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IE', N'Ireland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IL', N'Israel')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IN', N'India')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IO', N'British Indian Ocean Territory')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IQ', N'Iraq')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IR', N'Iran')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IS', N'Iceland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'IT', N'Italy')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'JM', N'Jamaica')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'JO', N'Jordan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'JP', N'Japan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KE', N'Kenya')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KG', N'Kyrgyzstan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KH', N'Cambodia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KI', N'Kiribati')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KM', N'Comoros')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KN', N'Saint Kitts and Nevis')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KP', N'North Korea')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KR', N'Korea')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KW', N'Kuwait')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KY', N'Cayman Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'KZ', N'Kazakhstan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LA', N'Laos')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LB', N'Lebanon')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LC', N'Saint Lucia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LI', N'Liechtenstein')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LK', N'Sri Lanka')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LR', N'Liberia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LS', N'Lesotho')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LT', N'Lithuania')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LU', N'Luxembourg')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LV', N'Latvia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'LY', N'Libya')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MA', N'Morocco')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MC', N'Monaco')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MD', N'Moldova')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MG', N'Madagascar')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MH', N'Marshall Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MK', N'Macedonia, Former Yuslav Republic of')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ML', N'Mali')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MM', N'Myanmar')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MN', N'Monlia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MO', N'Macao SAR')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MP', N'Northern Mariana Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MQ', N'Martinique')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MR', N'Mauritania')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MS', N'Montserrat')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MT', N'Malta')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MU', N'Mauritius')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MV', N'Maldives')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MW', N'Malawi')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MX', N'Mexico')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MY', N'Malaysia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'MZ', N'Mozambique')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NA', N'Namibia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NC', N'New Caledonia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NE', N'Niger')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NF', N'Norfolk Island')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NG', N'Nigeria')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NI', N'Nicaragua')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NL', N'Netherlands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NO', N'Norway')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NP', N'Nepal')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NR', N'Nauru')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NU', N'Niue')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'NZ', N'New Zealand')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'OM', N'Oman')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PA', N'Panama')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PE', N'Peru')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PF', N'French Polynesia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PG', N'Papua New Guinea')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PH', N'Philippines')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PK', N'Pakistan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PL', N'Poland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PM', N'Saint Pierre and Miquelon')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PN', N'Pitcairn Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PR', N'Puerto Rico')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PS', N'Palestinian Authority')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PT', N'Portugal')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PW', N'Palau')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'PY', N'Paraguay')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'QA', N'Qatar')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'RE', N'Réunion')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'RO', N'Romania')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'RU', N'Russia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'RW', N'Rwanda')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SA', N'Saudi Arabia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SB', N'Solomon Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SC', N'Seychelles')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SD', N'Sudan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SE', N'Sweden')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SG', N'Singapore')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SH', N'Saint Helena')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SI', N'Slovenia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SJ', N'Svalbard and Jan Mayen')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SK', N'Slovakia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SL', N'Sierra Leone')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SM', N'San Marino')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SN', N'Senegal')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SO', N'Somalia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SR', N'Suriname')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ST', N'São Tomé and Príncipe')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SV', N'El Salvador')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SY', N'Syria')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'SZ', N'Swaziland')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TC', N'Turks and Caicos Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TD', N'Chad')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TF', N'French Southern and Antarctic Lands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TG', N'To')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TH', N'Thailand')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TJ', N'Tajikistan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TK', N'Tokelau')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TL', N'Timor-Leste')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TM', N'Turkmenistan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TN', N'Tunisia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TO', N'Tonga')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TR', N'Turkey')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TT', N'Trinidad and Toba')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TV', N'Tuvalu')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TW', N'Taiwan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'TZ', N'Tanzania')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'UA', N'Ukraine')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'UG', N'Uganda')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'UM', N'U.S. Minor Outlying Islands')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'US', N'United States')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'UY', N'Uruguay')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'UZ', N'Uzbekistan')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VA', N'Vatican City')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VC', N'Saint Vincent and the Grenadine')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VE', N'Venezuela')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VG', N'Virgin Islands, British')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VI', N'Virgin Islands, U.S.')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VN', N'Vietnam')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'VU', N'Vanuatu')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'WF', N'Wallis and Futuna')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'WS', N'Samoa')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'YE', N'Yemen')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'YT', N'Mayotte')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ZA', N'South Africa')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ZM', N'Zambia')
    INSERT CountryRegion (CountryRegionCode, Name) VALUES (N'ZW', N'Zimbabwe')
END