IF NOT EXISTS (SELECT TOP 1 1 FROM ProductSubcategory)
BEGIN
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (1, 'Mountain Bikes')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (1, 'Road Bikes')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (1, 'Touring Bikes')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Handlebars')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Bottom Brackets')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Brakes')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Chains')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Cranksets')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Derailleurs')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Forks')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Headsets')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Mountain Frames')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Pedals')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Road Frames')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Saddles')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Touring Frames')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (2, 'Wheels')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Bib-Shorts')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Caps')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Gloves')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Jerseys')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Shorts')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Socks')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Tights')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (3, 'Vests')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Bike Racks')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Bike Stands')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Bottles and Cages')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Cleaners')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Fenders')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Helmets')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Hydration Packs')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Lights')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Locks')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Panniers')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Pumps')
	INSERT INTO ProductSubcategory (ProductCategoryID, Name) VALUES (4, 'Tires and Tubes')
END