IF NOT EXISTS (SELECT TOP 1 1 FROM UnitMeasure)
BEGIN
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('BOX', 'Boxes', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('BTL', 'Bottle', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('C', 'Celsius', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CAN', 'Canister', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CAR', 'Carton', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CBM', 'Cubic meters', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CCM', 'Cubic centimeter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CDM', 'Cubic centimeter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CM', 'Centimeter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CM2', 'Square centimeter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CR', 'Crate', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CS', 'Case', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('CTN', 'Container', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('DM', 'Decimeter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('DZ', 'Dozen', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('EA', 'Each', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('FT3', 'Cubic foot', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('G', 'Gram', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('GAL', 'Gallon', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('IN', 'Inch', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('KG', 'Kilogram', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('KGV', 'Kilogram/cubic meter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('KM', 'Kilometer', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('KT', 'Kiloton', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('L', 'Liter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('LB', 'US pound', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('M', 'Meter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('M2', 'Square meter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('M3', 'Cubic meter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('MG', 'Milligram', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('ML', 'Milliliter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('MM', 'Millimeter', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('OZ', 'Ounces', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('PAK', 'Pack', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('PAL', 'Pallet', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('PC', 'Piece', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('PCT', 'Percentage', GETDATE())
	INSERT INTO UnitMeasure (UnitMeasureCode, Name, ModifiedDate) VALUES ('PT', 'Pint, US liquid', GETDATE())
END