replicaCount: 1
pathBase: /employee-api/
serviceName: employee-api

image:
  repository: cradventureworks.azurecr.io/adventureworks_employeeapi
  tag: latest
  pullPolicy: Always

db: sqldb-adv-hr

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /employee-api/liveness
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80
  readiness:
    path: /employee-api/hc
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80