replicaCount: 1
pathBase: /salesorder-api/
serviceName: salesorder-api
authority: k8s-local.adventureworks.com/identityserver/

image:
  repository: ngruson/adventureworks_salesorderapi
  tag: latest
  pullPolicy: IfNotPresent

db: sqldb-adv-salesorder

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /salesorder-api/liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /salesorder-api/hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 30
    port: 80