replicaCount: 1
pathBase: /salesorder-api/
serviceName: salesorder-api

image:
  repository: cradventureworks.azurecr.io/adventureworks_salesorderapi
  tag: latest
  pullPolicy: Always

db: sqldb-adv-sales

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /salesorder-api/liveness
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80
  readiness:
    path: /salesorder-api/hc
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80