{{- $name := include "employee-api.fullname" . -}}
{{- $db := .Values.db -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ $name }}-secrets"
data:
  ConnectionStrings__DbConnection: {{ with .Values.global.inf.sql.common -}}
    {{- list "Server=" .host ";Database=" $db ";User Id=" .user ";Password=" .pwd | join "" | b64enc | quote -}}
  {{- end -}}