//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AW.UI.Web.Internal.SalesPersonService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.aw.com/SalesPersonService/1.0", ConfigurationName="AW.UI.Web.Internal.SalesPersonService.ISalesPersonService")]
    public interface ISalesPersonService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="ListSalesPersons", ReplyAction="ListSalesPersons")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsResponse> ListSalesPersonsAsync(AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSalesPerson", ReplyAction="GetSalesPerson")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AW.UI.Web.Internal.SalesPersonService.GetSalesPersonResponseGetSalesPersonResult> GetSalesPersonAsync(AW.UI.Web.Internal.SalesPersonService.GetSalesPersonRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://services.aw.com/SalesPersonService/1.0")]
    public partial class ListSalesPersonsRequest
    {
        
        private string territoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Territory
        {
            get
            {
                return this.territoryField;
            }
            set
            {
                this.territoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SalesPersonDto", Namespace="http://services.aw.com/SalesPersonService/1.0/GetSalesPerson")]
    public partial class SalesPersonDto1
    {
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string fullNameField;
        
        private string salesTerritoryNameField;
        
        private System.Nullable<decimal> salesQuotaField;
        
        private decimal bonusField;
        
        private decimal commissionPctField;
        
        private decimal salesYTDField;
        
        private decimal salesLastYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SalesTerritoryName
        {
            get
            {
                return this.salesTerritoryNameField;
            }
            set
            {
                this.salesTerritoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> SalesQuota
        {
            get
            {
                return this.salesQuotaField;
            }
            set
            {
                this.salesQuotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal CommissionPct
        {
            get
            {
                return this.commissionPctField;
            }
            set
            {
                this.commissionPctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal SalesYTD
        {
            get
            {
                return this.salesYTDField;
            }
            set
            {
                this.salesYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal SalesLastYear
        {
            get
            {
                return this.salesLastYearField;
            }
            set
            {
                this.salesLastYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aw.com/SalesPersonService/1.0/ListSalesPersons")]
    public partial class SalesPersonDto
    {
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string fullNameField;
        
        private string salesTerritoryNameField;
        
        private System.Nullable<decimal> salesQuotaField;
        
        private decimal bonusField;
        
        private decimal commissionPctField;
        
        private decimal salesYTDField;
        
        private decimal salesLastYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SalesTerritoryName
        {
            get
            {
                return this.salesTerritoryNameField;
            }
            set
            {
                this.salesTerritoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> SalesQuota
        {
            get
            {
                return this.salesQuotaField;
            }
            set
            {
                this.salesQuotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal CommissionPct
        {
            get
            {
                return this.commissionPctField;
            }
            set
            {
                this.commissionPctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal SalesYTD
        {
            get
            {
                return this.salesYTDField;
            }
            set
            {
                this.salesYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal SalesLastYear
        {
            get
            {
                return this.salesLastYearField;
            }
            set
            {
                this.salesLastYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListSalesPersons", WrapperNamespace="http://services.aw.com/SalesPersonService/1.0", IsWrapped=true)]
    public partial class ListSalesPersonsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aw.com/SalesPersonService/1.0", Order=0)]
        public AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest request;
        
        public ListSalesPersonsRequest1()
        {
        }
        
        public ListSalesPersonsRequest1(AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListSalesPersonsResponse", WrapperNamespace="http://services.aw.com/SalesPersonService/1.0", IsWrapped=true)]
    public partial class ListSalesPersonsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aw.com/SalesPersonService/1.0", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SalesPersons", Namespace="http://services.aw.com/SalesPersonService/1.0/ListSalesPersons", IsNullable=false)]
        public AW.UI.Web.Internal.SalesPersonService.SalesPersonDto[] ListSalesPersonsResult;
        
        public ListSalesPersonsResponse()
        {
        }
        
        public ListSalesPersonsResponse(AW.UI.Web.Internal.SalesPersonService.SalesPersonDto[] ListSalesPersonsResult)
        {
            this.ListSalesPersonsResult = ListSalesPersonsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://services.aw.com/SalesPersonService/1.0")]
    public partial class GetSalesPersonRequest
    {
        
        private string fullNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://services.aw.com/SalesPersonService/1.0")]
    public partial class GetSalesPersonResponseGetSalesPersonResult
    {
        
        private SalesPersonDto1 salesPersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.aw.com/SalesPersonService/1.0/GetSalesPerson", Order=0)]
        public SalesPersonDto1 SalesPerson
        {
            get
            {
                return this.salesPersonField;
            }
            set
            {
                this.salesPersonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISalesPersonServiceChannel : AW.UI.Web.Internal.SalesPersonService.ISalesPersonService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SalesPersonServiceClient : System.ServiceModel.ClientBase<AW.UI.Web.Internal.SalesPersonService.ISalesPersonService>, AW.UI.Web.Internal.SalesPersonService.ISalesPersonService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SalesPersonServiceClient() : 
                base(SalesPersonServiceClient.GetDefaultBinding(), SalesPersonServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISalesPersonService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesPersonServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SalesPersonServiceClient.GetBindingForEndpoint(endpointConfiguration), SalesPersonServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesPersonServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SalesPersonServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesPersonServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SalesPersonServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesPersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsResponse> AW.UI.Web.Internal.SalesPersonService.ISalesPersonService.ListSalesPersonsAsync(AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest1 request)
        {
            return base.Channel.ListSalesPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsResponse> ListSalesPersonsAsync(AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest request)
        {
            AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest1 inValue = new AW.UI.Web.Internal.SalesPersonService.ListSalesPersonsRequest1();
            inValue.request = request;
            return ((AW.UI.Web.Internal.SalesPersonService.ISalesPersonService)(this)).ListSalesPersonsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AW.UI.Web.Internal.SalesPersonService.GetSalesPersonResponseGetSalesPersonResult> GetSalesPersonAsync(AW.UI.Web.Internal.SalesPersonService.GetSalesPersonRequest request)
        {
            return base.Channel.GetSalesPersonAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISalesPersonService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISalesPersonService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/AW.SalesPersonService/SalesPersonService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SalesPersonServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISalesPersonService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SalesPersonServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISalesPersonService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISalesPersonService,
        }
    }
}
