replicaCount: 1
pathBase: /product-api/
serviceName: product-api

image:
  repository: ngruson/adventureworks_productapi
  tag: latest
  pullPolicy: IfNotPresent

db: sqldb-adv-product

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /product-api/liveness
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80
  readiness:
    path: /product-api/hc
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80