apiVersion: v1
kind: ConfigMap
metadata:
  name: adventureworks-basket-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: http://*:5000
  RedisConnectionString: basket-redis-service
  AzureServiceBusEnabled: "false"
  EventBusConnection: rabbitmq
  EventBusUserName: admin