kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-configuration
  namespace: ingress-nginx
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
  proxy-busy-buffers-size: "256k"
  client-header-buffer-size: "64k"
  http2-max-field-size: "16k"
  http2-max-header-size: "128k"
  large-client-header-buffers: "8 64k"