apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventureworks-rabbitmq
spec:
  selector:
    matchLabels:
      app: adventureworks-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: adventureworks-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: adventureworks-rabbitmq
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672