apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventureworks-basket-redis
spec:
  selector:
    matchLabels:
      app: adventureworks-basket-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: adventureworks-basket-redis
    spec:
      containers:
      - name: basket-redis
        image: redis:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: basket-redis-service
spec:
  selector:
    app: adventureworks-basket-redis
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379