 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: adventureworks-ingress
 spec:
   tls:
   - hosts:
     - k8s-local.adventureworks.com
     secretName: local-tls
   rules:
   - host: k8s-local.adventureworks.com
     http:
       paths:
       - pathType: Prefix
         path: /
         backend:
           service:
             name: referencedata-api-service
             port:
               number: 5000

       - pathType: Prefix
         path: /customer-api/
         backend:
           service:
             name: customer-api-service
             port:
               number: 5000

       - pathType: Prefix
         path: /product-api/
         backend:
           service:
             name: product-api-service
             port:
               number: 5000
            
       - pathType: Prefix
         path: /salesperson-api/
         backend:
           service:
             name: salesperson-api-service
             port:
               number: 5000