{{- $releaseName := .Release.Name -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "adventureworks.fullname" . }}-ingress
  labels:
    app: {{ include "adventureworks.name" . }}
    chart: {{ include "adventureworks.chart" . }}
    release: {{ $releaseName }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
spec:
  #ingressClassName: {{ $releaseName }}-{{ .Values.ingress.className }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
   {{- range .Values.ingress.hosts }}
    - host: {{ $releaseName }}.{{ .host }}
      http:
        paths:
        {{- range .paths }}
          - pathType: Prefix
            path: {{ .path.value }}
            backend:
              service:
                name: {{ $releaseName }}-{{ .path.serviceName }}
                port:
                  number: {{ .path.servicePort }}
  {{- end }}
{{- end }}