{{- $releaseName := .Release.Name -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "adventureworks.fullname" . }}-ingress
  labels:
    app: {{ include "adventureworks.name" . }}
    chart: {{ include "adventureworks.chart" . }}
    release: {{ $releaseName }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
spec:
  tls:  
    - hosts:
      - {{ .Values.global.inf.ingress.host }}
      secretName: {{ .Values.global.inf.ingress.secretName }}
  rules:
    - host: {{ .Values.global.inf.ingress.host }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - pathType: Prefix
            path: {{ .path.value }}
            backend:
              service:
                name: {{ $releaseName }}-{{ .path.serviceName }}
                port:
                  number: {{ .path.servicePort }}
        {{- end }}