{{- $name := include "basket-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-config"
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  AuthN__Authority: https://{{ .Values.global.inf.authority }}
  ElasticSearchUri: http://{{ .Release.Name }}-elasticsearch-master:9200
  EventBusConnection: {{ .Release.Name }}-rabbitmq
  RedisConnectionString: {{ .Release.Name }}-redis-master