{{- $name := include "basket-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-config"
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  AuthN__Authority: {{ printf "https://%s.%s" .Release.Name .Values.authority }}  
  ElasticSearchUri: http://dev-elasticsearch-master:9200
  EventBusConnection: dev-rabbitmq
  RedisConnectionString: dev-redis-master