{{- $name := include "basket-api.fullname" . -}}
{{- $releaseName := $.Release.Name -}}
{{- $rabbitmqUser := .Values.global.inf.rabbitmq.user }}
{{- $rabbitmqPassword := .Values.global.inf.rabbitmq.password }}
{{- $redisPassword := .Values.global.inf.redis.password }}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ $name }}-secrets"
data:
  RedisPassword: {{ $redisPassword | b64enc | quote }}
  EventBusUserName: {{ $rabbitmqUser | b64enc | quote }}
  EventBusPassword: {{ $rabbitmqPassword | b64enc | quote }}