{{- $name := include "customer-db.fullname" . -}}
{{- $db := .Values.db -}}

{{- if .Values.global.app.db.customer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $name }}-secrets"
data:
  SA_PASSWORD: {{ with .Values.global.inf.sql.common -}}
    {{- .sa_password | b64enc | quote -}}
  {{- end -}}
{{- end }}