{{- $name := include "mvc-internal.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-config"
  labels:
    app: {{ template "mvc-internal.name" . }}
    chart: {{ template "mvc-internal.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  AuthN__Authority: https://{{ .Values.global.inf.authority }}
  AuthN__ClientId: {{ .Values.clientId }}
  AuthN__ClientSecret: {{ .Values.clientSecret }}
  ElasticSearchUri: http://{{ .Release.Name }}-elasticsearch-master:9200
  CustomerAPI__Uri: https://{{ .Values.global.inf.ingress.host }}{{ .Values.customer_api }}
  ReferenceDataAPI__Uri: http://localhost:8080/
  SalesOrderAPI__Uri: https://{{ .Values.global.inf.ingress.host }}{{ .Values.salesorder_api }}
  SalesPersonAPI__Uri: https://{{ .Values.global.inf.ingress.host }}{{ .Values.salesperson_api }}
  envoy-config: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              #codec_type: http1
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/referencedata-api"
                    route:
                      cluster: referencedata-api
              # http_filters:
              # - name: envoy.router
              #   typed_config: {}
      clusters:
      - name: referencedata-api
        type: STRICT_DNS
        load_assignment:
          cluster_name: referencedata-api
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-referencedata-api
                    port_value: 80