CREATE TABLE [SalesPerson](
	[PersonID] [int] IDENTITY(1,1) NOT NULL,
	[Territory] [nvarchar](50) NULL
 CONSTRAINT [PK_SalesPerson_PersonID] PRIMARY KEY CLUSTERED
(
	[PersonID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SalesPerson] ADD CONSTRAINT [FK_SalesPerson_Person_PersonID] FOREIGN KEY([PersonID])
REFERENCES [Person] ([PersonID])
GO

ALTER TABLE [SalesPerson] CHECK CONSTRAINT [FK_SalesPerson_Person_PersonID]
GO