replicaCount: 1
pathBase: /referencedata-api/
serviceName: referencedata-api
authority: k8s-local.adventureworks.com/identityserver/

image:
  repository: ngruson/adventureworks_referencedataapi
  tag: latest
  pullPolicy: IfNotPresent

db: sqldb-adv-referencedata

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /referencedata-api/liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /referencedata-api/hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 30
    port: 80