replicaCount: 1
pathBase: /referencedata-api/
serviceName: referencedata-api

image:
  repository: cradventureworks.azurecr.io/adventureworks_referencedataapi
  tag: latest
  pullPolicy: Always

db: sqldb-adv-referencedata

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /referencedata-api/liveness
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80
  readiness:
    path: /referencedata-api/hc
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80