{{- $name := include "ui-web-admin-mvc.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-config"
  labels:
    app: {{ template "ui-web-admin-mvc.name" . }}
    chart: {{ template "ui-web-admin-mvc.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  AuthN__IdP: {{ .Values.global.inf.authN.idP }}
  AuthN__Scopes: {{- range .Values.global.inf.authN.adminMvc.scopes }} {{.}} {{- end }}
  AuthN__ApiScopes__CustomerApiRead: {{ .Values.global.inf.authN.adminMvc.apiScopes.customerApiRead }}
  AuthN__ApiScopes__ReferenceDataApiRead: {{ .Values.global.inf.authN.adminMvc.apiScopes.referenceDataApiRead }}
  AuthN__ApiScopes__SalesOrderApiRead: {{ .Values.global.inf.authN.adminMvc.apiScopes.salesOrderApiRead }}
  AuthN__ApiScopes__SalesPersonApiRead: {{ .Values.global.inf.authN.adminMvc.apiScopes.salesPersonApiRead }}
  AuthN__AzureAd__Instance: {{ .Values.global.inf.authN.aad.instance }}
  AuthN__AzureAd__Domain: {{ .Values.global.inf.authN.aad.domain }}
  AuthN__AzureAd__TenantId: {{ .Values.global.inf.authN.aad.tenantId }}
  AuthN__AzureAd__ClientId: {{ .Values.global.inf.authN.adminMvc.clientId }}
  AuthN__AzureAd__ClientSecret: {{ .Values.global.inf.authN.adminMvc.clientSecret }}
  AuthN__AzureAd__CallbackPath: {{ .Values.global.inf.authN.adminMvc.callbackPath }}
  AuthN__AzureAd__SignedOutCallbackPath: {{ .Values.global.inf.authN.adminMvc.signedOutCallbackPath }}
  AuthN__IdSrv__Authority: https://{{ .Values.global.inf.authority }}
  AuthN__IdSrv__ClientId: {{ .Values.authN.idSrv.clientId }}
  AuthN__IdSrv__ClientSecret: {{ .Values.authN.idSrv.clientSecret }}
  ElasticSearchUri: http://localhost:8080
  CustomerAPI__Uri: http://localhost:8080/customer-api/
  ReferenceDataAPI__Uri: http://localhost:8080/referencedata-api/
  SalesOrderAPI__Uri: http://localhost:8080/salesorder-api/
  SalesPersonAPI__Uri: http://localhost:8080/salesperson-api/
  envoy-config: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: http1
              stat_prefix: forward_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:                  
                  - match:
                      prefix: "/customer-api"
                    route:
                      cluster: customer-api
                  - match:
                      prefix: "/referencedata-api"
                    route:
                      cluster: referencedata-api
                  - match:
                      prefix: "/salesorder-api"
                    route:
                      cluster: salesorder-api
                  - match:
                      prefix: "/salesperson-api"
                    route:
                      cluster: salesperson-api
                  - match:
                      prefix: "/"
                    route:
                      cluster: elasticsearch
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: customer-api
          type: strict_dns
          load_assignment:
            cluster_name: customer-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-customer-api
                        port_value: 80
        - name: elasticsearch
          type: strict_dns
          load_assignment:
            cluster_name: elasticsearch
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-elasticsearch-master
                        port_value: 9200
        - name: referencedata-api
          type: strict_dns
          load_assignment:
            cluster_name: referencedata-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-referencedata-api
                        port_value: 80
        - name: salesorder-api
          type: strict_dns
          load_assignment:
            cluster_name: salesorder-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-salesorder-api
                        port_value: 80
        - name: salesperson-api
          type: strict_dns
          load_assignment:
            cluster_name: salesperson-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-salesperson-api
                        port_value: 80

    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
          overload:
            global_downstream_max_connections: 50000