version: '3.4'

services:

  reverseproxy:
      build:
        context: .
        dockerfile: nginx/nginx.Dockerfile
      depends_on:
        - adventureworks.identityserver        
        - adventureworks.customer-api
      ports:
        - "44395:44395"

  adventureworks.identityserver:
    build:
        context: .
        dockerfile: Services/IdentityServer/src/AW.Services.IdentityServer/Dockerfile
    environment:
    - ASPNETCORE_URLS=http://*:80
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "5005:80"

  adventureworks.customer-api:
    build:
      context: .
      dockerfile: Services/Customer/src/AW.Services.Customer.REST.API/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "5006:80"