{{- $name := include "mvc-store.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-config"
  labels:
    app: {{ template "mvc-store.name" . }}
    chart: {{ template "mvc-store.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  AuthN__Authority: https://{{ .Values.global.inf.authority }}
  ElasticSearchUri: http://{{ .Release.Name }}-elasticsearch-master:9200
  BasketAPI__Uri: https://{{ .Values.global.inf.ingress.host }}{{ .Values.basket_api }}
  ProductAPI__Uri: https://{{ .Values.global.inf.ingress.host }}{{ .Values.product_api }}