{{- $name := include "mvc-store.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-config"
  labels:
    app: {{ template "mvc-store.name" . }}
    chart: {{ template "mvc-store.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  AuthN__Authority: https://{{ .Values.global.inf.authority }}
  AuthN__ClientId: {{ .Values.clientId }}
  AuthN__ClientSecret: {{ .Values.clientSecret }}
  ElasticSearchUri: http://localhost:8080
  BasketAPI__Uri: http://localhost:8080/basket-api/
  CustomerAPI__Uri: http://localhost:8080/customer-api/
  ProductAPI__Uri: http://localhost:8080/product-api/
  ReferenceDataAPI__Uri: http://localhost:8080/referencedata-api/
  envoy-config: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: http1
              stat_prefix: forward_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:                  
                  - match:
                      prefix: "/basket-api"
                    route:
                      cluster: basket-api
                  - match:
                      prefix: "/customer-api"
                    route:
                      cluster: customer-api
                  - match:
                      prefix: "/product-api"
                    route:
                      cluster: product-api
                  - match:
                      prefix: "/referencedata-api"
                    route:
                      cluster: referencedata-api
                  - match:
                      prefix: "/"
                    route:
                      cluster: elasticsearch
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: basket-api
          type: strict_dns
          load_assignment:
            cluster_name: basket-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-basket-api
                        port_value: 80
        - name: customer-api
          type: strict_dns
          load_assignment:
            cluster_name: customer-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-customer-api
                        port_value: 80
        - name: elasticsearch
          type: strict_dns
          load_assignment:
            cluster_name: elasticsearch
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-elasticsearch-master
                        port_value: 9200
        - name: product-api
          type: strict_dns
          load_assignment:
            cluster_name: product-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-product-api
                        port_value: 80
        - name: referencedata-api
          type: strict_dns
          load_assignment:
            cluster_name: referencedata-api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Release.Name }}-referencedata-api
                        port_value: 80

    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
          overload:
            global_downstream_max_connections: 50000