replicaCount: 1
pathBase: /identityserver/
serviceName: identityserver

image:
  repository: adventureworks_identityserver
  tag: latest
  pullPolicy: Always

db: sqldb-adv-identityserver

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /identityserver/liveness
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80
  readiness:
    path: /identityserver/hc
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 80