name: basket-api

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml

env:
  DOTNET_VERSION: 7.0.x
  REGISTRY_NAME: cradventureworks
  APP_NAME: adventureworks_basketapi

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
   
      - name: Build and run unit tests
        run: |

          cd src/Services/Basket

          dotnet build src/AW.Services.Basket.Core/AW.Services.Basket.Core.csproj
          dotnet build tests/AW.Services.Basket.Core.UnitTests/AW.Services.Basket.Core.UnitTests.csproj
          dotnet test tests/AW.Services.Basket.Core.UnitTests/AW.Services.Basket.Core.UnitTests.csproj --no-build --no-restore

          dotnet build src/AW.Services.Basket.REST.API/AW.Services.Basket.REST.API.csproj
          dotnet build tests/AW.Services.Basket.REST.API.UnitTests/AW.Services.Basket.REST.API.UnitTests.csproj
          dotnet test tests/AW.Services.Basket.REST.API.UnitTests/AW.Services.Basket.REST.API.UnitTests.csproj --no-build --no-restore

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build the Docker image      
        run: |
          cd src
          docker build -f Services/Basket/src/AW.Services.Basket.REST.API/Dockerfile -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest .

      - name: Push Image to Docker
        run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest