name: build-all

# Controls when the action will run. 
on:
  workflow_dispatch:

env:
  DOTNET_VERSION: 7.0.x
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Restore NuGet packages
        run: nuget restore src\AdventureWorks.sln
          
      - name: Begin Sonar scan
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:ngruson /k:ngruson_AdventureWorks /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io

      - name: Build ConsoleTools and run unit tests
        run: |
          dotnet build src\ConsoleTools\tests\AW.ConsoleTools.UnitTests\AW.ConsoleTools.UnitTests.csproj --no-restore
          dotnet test src\ConsoleTools\tests\AW.ConsoleTools.UnitTests\AW.ConsoleTools.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build Infrastructure and run unit tests
        run: |
          dotnet build src\Services\Infrastructure\tests\AW.Services.Infrastructure.UnitTests\AW.Services.Infrastructure.UnitTests.csproj --no-restore
          dotnet test src\Services\Infrastructure\tests\AW.Services.Infrastructure.UnitTests\AW.Services.Infrastructure.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

          dotnet build src\Services\Infrastructure\tests\AW.Services.Infrastructure.EventBus.UnitTests\AW.Services.Infrastructure.EventBus.UnitTests.csproj --no-restore
          dotnet test src\Services\Infrastructure\tests\AW.Services.Infrastructure.EventBus.UnitTests\AW.Services.Infrastructure.EventBus.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build SharedKernel and run unit tests
        run: |
          dotnet build src\SharedKernel\tests\AW.SharedKernel.UnitTests\AW.SharedKernel.UnitTests.csproj --no-restore
          dotnet test src\SharedKernel\tests\AW.SharedKernel.UnitTests\AW.SharedKernel.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\SharedKernel\tests\AW.SharedKernel.Api.UnitTests\AW.SharedKernel.Api.UnitTests.csproj --no-restore
          dotnet test src\SharedKernel\tests\AW.SharedKernel.Api.UnitTests\AW.SharedKernel.Api.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\SharedKernel\tests\AW.Services.SharedKernel.UnitTests\AW.Services.SharedKernel.UnitTests.csproj --no-restore
          dotnet test src\Services\SharedKernel\tests\AW.Services.SharedKernel.UnitTests\AW.Services.SharedKernel.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

          dotnet build src\Services\SharedKernel\tests\AW.Services.SharedKernel.EFCore.UnitTests\AW.Services.SharedKernel.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\SharedKernel\tests\AW.Services.SharedKernel.EFCore.UnitTests\AW.Services.SharedKernel.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      
      - name: Build IdentityServer and run unit tests
        run: |
          dotnet build src\Services\IdentityServer\tests\AW.Services.IdentityServer.Core.UnitTests\AW.Services.IdentityServer.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\IdentityServer\tests\AW.Services.IdentityServer.Core.UnitTests\AW.Services.IdentityServer.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build Customer services and run unit tests
        run: |
          dotnet build src\Services\Customer\tests\AW.Services.Customer.Core.UnitTests\AW.Services.Customer.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\Customer\tests\AW.Services.Customer.Core.UnitTests\AW.Services.Customer.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Customer\tests\AW.Services.Customer.Infrastructure.EFCore.UnitTests\AW.Services.Customer.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\Customer\tests\AW.Services.Customer.Infrastructure.EFCore.UnitTests\AW.Services.Customer.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Customer\src\AW.Services.Customer.REST.API\AW.Services.Customer.REST.API.csproj --no-restore
          dotnet build src\Services\Customer\tests\AW.Services.Customer.REST.API.UnitTests\AW.Services.Customer.REST.API.UnitTests.csproj --no-restore          
          dotnet test src\Services\Customer\tests\AW.Services.Customer.REST.API.UnitTests\AW.Services.Customer.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

        - name: Build Human Resources services and run unit tests
        run: |
          dotnet build src\Services\HumanResources\tests\AW.Services.HumanResources.Core.UnitTests\AW.Services.HumanResources.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\HumanResources\tests\AW.Services.HumanResources.Core.UnitTests\AW.Services.HumanResources.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\HumanResources\tests\AW.Services.HumanResources.Infrastructure.EFCore.UnitTests\AW.Services.HumanResources.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\HumanResources\tests\AW.Services.HumanResources.Infrastructure.EFCore.UnitTests\AW.Services.HumanResources.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\HumanResources\src\AW.Services.HumanResources.Department.REST.API\AW.Services.HumanResources.Department.REST.API.csproj --no-restore
          dotnet build src\Services\HumanResources\tests\AW.Services.HumanResources.Employee.REST.API.UnitTests\AW.Services.HumanResources.Employee.REST.API.UnitTests.csproj --no-restore
          dotnet build src\Services\HumanResources\tests\AW.Services.HumanResources.Shift.REST.API.UnitTests\AW.Services.HumanResources.Shift.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\Customer\tests\AW.Services.HumanResources.Department.REST.API.UnitTests\AW.Services.HumanResources.Department.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          dotnet test src\Services\Customer\tests\AW.Services.HumanResources.Employee.REST.API.UnitTests\AW.Services.HumanResources.Employee.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          dotnet test src\Services\Customer\tests\AW.Services.HumanResources.Shift.REST.API.UnitTests\AW.Services.HumanResources.Shift.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build Product services and run unit tests
        run: |
          dotnet build src\Services\Product\tests\AW.Services.Product.Core.UnitTests\AW.Services.Product.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\Product\tests\AW.Services.Product.Core.UnitTests\AW.Services.Product.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Product\tests\AW.Services.Product.Infrastructure.EFCore.UnitTests\AW.Services.Product.Infrastructure.EFCore.UnitTests.csproj --no-restore                    
          dotnet test src\Services\Product\tests\AW.Services.Product.Infrastructure.EFCore.UnitTests\AW.Services.Product.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Product\src\AW.Services.Product.REST.API\AW.Services.Product.REST.API.csproj --no-restore
          dotnet build src\Services\Product\tests\AW.Services.Product.REST.API.UnitTests\AW.Services.Product.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\Product\tests\AW.Services.Product.REST.API.UnitTests\AW.Services.Product.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build ReferenceData services and run unit tests
        run: |
          dotnet build src\Services\ReferenceData\tests\AW.Services.ReferenceData.Core.UnitTests\AW.Services.ReferenceData.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.Core.UnitTests\AW.Services.ReferenceData.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\ReferenceData\tests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\ReferenceData\src\AW.Services.ReferenceData.REST.API\AW.Services.ReferenceData.REST.API.csproj --no-restore
          dotnet build src\Services\ReferenceData\tests\AW.Services.ReferenceData.REST.API.UnitTests\AW.Services.ReferenceData.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.REST.API.UnitTests\AW.Services.ReferenceData.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
      - name: Build Sales services and run unit tests
        run: |
          dotnet build src\Services\Sales\tests\AW.Services.Sales.Core.UnitTests\AW.Services.Sales.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\Sales\tests\AW.Services.Sales.Core.UnitTests\AW.Services.Sales.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Sales\tests\AW.Services.Sales.Infrastructure.EFCore.UnitTests\AW.Services.Sales.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\Sales\tests\AW.Services.Sales.Infrastructure.EFCore.UnitTests\AW.Services.Sales.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Sales\src\AW.Services.Sales.Order.REST.API\AW.Services.Sales.Order.REST.API.csproj --no-restore
          dotnet build src\Services\Sales\tests\AW.Services.Sales.Order.REST.API.UnitTests\AW.Services.Sales.Order.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\Sales\tests\AW.Services.Sales.Order.REST.API.UnitTests\AW.Services.Sales.Order.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

          dotnet build src\Services\Sales\src\AW.Services.Sales.SalesPerson.REST.API\AW.Services.Sales.SalesPerson.REST.API.csproj --no-restore
          dotnet build src\Services\Sales\tests\AW.Services.Sales.SalesPerson.REST.API.UnitTests\AW.Services.Sales.SalesPerson.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\Sales\tests\AW.Services.Sales.SalesPerson.REST.API.UnitTests\AW.Services.Sales.SalesPerson.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
        
      - name: Build UI and run unit tests
        run: |
          dotnet build src\UI\SharedKernel\tests\AW.UI.Web.SharedKernel.UnitTests\AW.UI.Web.SharedKernel.UnitTests.csproj --no-restore
          dotnet test src\UI\SharedKernel\tests\AW.UI.Web.SharedKernel.UnitTests\AW.UI.Web.SharedKernel.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

          dotnet build src\UI\Infrastructure\tests\AW.UI.Web.Infrastructure.UnitTests\AW.UI.Web.Infrastructure.UnitTests.csproj --no-restore
          dotnet test src\UI\Infrastructure\tests\AW.UI.Web.Infrastructure.UnitTests\AW.UI.Web.Infrastructure.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\UI\Internal\tests\AW.UI.Web.Internal.UnitTests\AW.UI.Web.Internal.UnitTests.csproj --no-restore
          dotnet test src\UI\Internal\tests\AW.UI.Web.Internal.UnitTests\AW.UI.Web.Internal.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\UI\Store\tests\AW.UI.Web.Store.UnitTests\AW.UI.Web.Store.UnitTests.csproj --no-restore
          dotnet test src\UI\Store\tests\AW.UI.Web.Store.UnitTests\AW.UI.Web.Store.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
