name: build-all

# Controls when the action will run. 
on:
  workflow_dispatch:

env:
  DOTNET_VERSION: 5.0.x
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Restore NuGet packages
        run: nuget restore src\AdventureWorks.sln
          
      - name: Begin Sonar scan
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:ngruson /k:ngruson_AdventureWorks /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io
         
      - name: Build SharedKernel and run unit tests
        run: |
          dotnet build src\SharedKernel\AW.SharedKernel.UnitTests\AW.SharedKernel.UnitTests.csproj --no-restore
          dotnet test src\SharedKernel\AW.SharedKernel.UnitTests\AW.SharedKernel.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      
      - name: Build Customer services and run unit tests
        run: |
          dotnet build src\Services\Customer\tests\AW.Services.Customer.Core.UnitTests\AW.Services.Customer.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\Customer\tests\AW.Services.Customer.Core.UnitTests\AW.Services.Customer.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          msbuild src\Services\Customer\tests\AW.Services.Customer.Infrastructure.EF6.UnitTests\AW.Services.Customer.Infrastructure.EF6.UnitTests.csproj
          dotnet test src\Services\Customer\tests\AW.Services.Customer.Infrastructure.EF6.UnitTests\AW.Services.Customer.Infrastructure.EF6.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Customer\tests\AW.Services.Customer.Infrastructure.EFCore.UnitTests\AW.Services.Customer.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\Customer\tests\AW.Services.Customer.Infrastructure.EFCore.UnitTests\AW.Services.Customer.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Customer\src\AW.Services.Customer.REST.API\AW.Services.Customer.REST.API.csproj --no-restore
          dotnet build src\Services\Customer\tests\AW.Services.Customer.REST.API.UnitTests\AW.Services.Customer.REST.API.UnitTests.csproj --no-restore          
          dotnet test src\Services\Customer\tests\AW.Services.Customer.REST.API.UnitTests\AW.Services.Customer.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          msbuild src\Services\Customer\src\AW.Services.Customer.WCF\AW.Services.Customer.WCF.csproj
          msbuild src\Services\Customer\tests\AW.Services.Customer.WCF.UnitTests\AW.Services.Customer.WCF.UnitTests.csproj
          dotnet test src\Services\Customer\tests\AW.Services.Customer.WCF.UnitTests\AW.Services.Customer.WCF.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build Product services and run unit tests
        run: |
          dotnet build src\Services\Product\tests\AW.Services.Product.Core.UnitTests\AW.Services.Product.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\Product\tests\AW.Services.Product.Core.UnitTests\AW.Services.Product.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          msbuild src\Services\Product\tests\AW.Services.Product.Infrastructure.EF6.UnitTests\AW.Services.Product.Infrastructure.EF6.UnitTests.csproj
          dotnet test src\Services\Product\tests\AW.Services.Product.Infrastructure.EF6.UnitTests\AW.Services.Product.Infrastructure.EF6.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Product\tests\AW.Services.Product.Infrastructure.EFCore.UnitTests\AW.Services.Product.Infrastructure.EFCore.UnitTests.csproj --no-restore                    
          dotnet test src\Services\Product\tests\AW.Services.Product.Infrastructure.EFCore.UnitTests\AW.Services.Product.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\Product\src\AW.Services.Product.REST.API\AW.Services.Product.REST.API.csproj --no-restore
          dotnet build src\Services\Product\tests\AW.Services.Product.REST.API.UnitTests\AW.Services.Product.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\Product\tests\AW.Services.Product.REST.API.UnitTests\AW.Services.Product.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          msbuild src\Services\Product\src\AW.Services.Product.WCF\AW.Services.Product.WCF.csproj
          msbuild src\Services\Product\tests\AW.Services.Product.WCF.UnitTests\AW.Services.Product.WCF.UnitTests.csproj
          dotnet test src\Services\Product\tests\AW.Services.Product.WCF.UnitTests\AW.Services.Product.WCF.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

      - name: Build ReferenceData services and run unit tests
        run: |
          dotnet build src\Services\ReferenceData\tests\AW.Services.ReferenceData.Core.UnitTests\AW.Services.ReferenceData.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.Core.UnitTests\AW.Services.ReferenceData.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
                    
          msbuild src\Services\ReferenceData\tests\AW.Services.ReferenceData.Infrastructure.EF6.UnitTests\AW.Services.ReferenceData.Infrastructure.EF6.UnitTests.csproj
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.Infrastructure.EF6.UnitTests\AW.Services.ReferenceData.Infrastructure.EF6.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\ReferenceData\tests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests\AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\ReferenceData\src\AW.Services.ReferenceData.REST.API\AW.Services.ReferenceData.REST.API.csproj --no-restore
          dotnet build src\Services\ReferenceData\tests\AW.Services.ReferenceData.REST.API.UnitTests\AW.Services.ReferenceData.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.REST.API.UnitTests\AW.Services.ReferenceData.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          nuget restore src\Services\ReferenceData\src\AW.Services.ReferenceData.WCF\packages.config
          msbuild src\Services\ReferenceData\src\AW.Services.ReferenceData.WCF\AW.Services.ReferenceData.WCF.csproj
          msbuild src\Services\ReferenceData\tests\AW.Services.ReferenceData.WCF.UnitTests\AW.Services.ReferenceData.WCF.UnitTests.csproj
          dotnet test src\Services\ReferenceData\tests\AW.Services.ReferenceData.WCF.UnitTests\AW.Services.ReferenceData.WCF.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
      - name: Build SalesOrder services and run unit tests
        run: |
          dotnet build src\Services\SalesOrder\tests\AW.Services.SalesOrder.Core.UnitTests\AW.Services.SalesOrder.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\SalesOrder\tests\AW.Services.SalesOrder.Core.UnitTests\AW.Services.SalesOrder.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          msbuild src\Services\SalesOrder\tests\AW.Services.SalesOrder.Infrastructure.EF6.UnitTests\AW.Services.SalesOrder.Infrastructure.EF6.UnitTests.csproj
          dotnet test src\Services\SalesOrder\tests\AW.Services.SalesOrder.Infrastructure.EF6.UnitTests\AW.Services.SalesOrder.Infrastructure.EF6.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\SalesOrder\tests\AW.Services.SalesOrder.Infrastructure.EFCore.UnitTests\AW.Services.SalesOrder.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\SalesOrder\tests\AW.Services.SalesOrder.Infrastructure.EFCore.UnitTests\AW.Services.SalesOrder.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\SalesOrder\src\AW.Services.SalesOrder.REST.API\AW.Services.SalesOrder.REST.API.csproj --no-restore
          dotnet build src\Services\SalesOrder\tests\AW.Services.SalesOrder.REST.API.UnitTests\AW.Services.SalesOrder.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\SalesOrder\tests\AW.Services.SalesOrder.REST.API.UnitTests\AW.Services.SalesOrder.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          nuget restore src\Services\SalesOrder\src\AW.Services.SalesOrder.WCF\packages.config
          msbuild src\Services\SalesOrder\src\AW.Services.SalesOrder.WCF\AW.Services.SalesOrder.WCF.csproj
          msbuild src\Services\SalesOrder\tests\AW.Services.SalesOrder.WCF.UnitTests\AW.Services.SalesOrder.WCF.UnitTests.csproj
          dotnet test src\Services\SalesOrder\tests\AW.Services.SalesOrder.WCF.UnitTests\AW.Services.SalesOrder.WCF.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
        
      - name: Build SalesPerson services and run unit tests
        run: |
          dotnet build src\Services\SalesPerson\tests\AW.Services.SalesPerson.Core.UnitTests\AW.Services.SalesPerson.Core.UnitTests.csproj --no-restore
          dotnet test src\Services\SalesPerson\tests\AW.Services.SalesPerson.Core.UnitTests\AW.Services.SalesPerson.Core.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          msbuild src\Services\SalesPerson\tests\AW.Services.SalesPerson.Infrastructure.EF6.UnitTests\AW.Services.SalesPerson.Infrastructure.EF6.UnitTests.csproj
          dotnet test src\Services\SalesPerson\tests\AW.Services.SalesPerson.Infrastructure.EF6.UnitTests\AW.Services.SalesPerson.Infrastructure.EF6.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\SalesPerson\tests\AW.Services.SalesPerson.Infrastructure.EFCore.UnitTests\AW.Services.SalesPerson.Infrastructure.EFCore.UnitTests.csproj --no-restore
          dotnet test src\Services\SalesPerson\tests\AW.Services.SalesPerson.Infrastructure.EFCore.UnitTests\AW.Services.SalesPerson.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\Services\SalesPerson\src\AW.Services.SalesPerson.REST.API\AW.Services.SalesPerson.REST.API.csproj --no-restore
          dotnet build src\Services\SalesPerson\tests\AW.Services.SalesPerson.REST.API.UnitTests\AW.Services.SalesPerson.REST.API.UnitTests.csproj --no-restore
          dotnet test src\Services\SalesPerson\tests\AW.Services.SalesPerson.REST.API.UnitTests\AW.Services.SalesPerson.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          nuget restore src\Services\SalesPerson\src\AW.Services.SalesPerson.WCF\packages.config
          msbuild src\Services\SalesPerson\src\AW.Services.SalesPerson.WCF\AW.Services.SalesPerson.WCF.csproj
          msbuild src\Services\SalesPerson\tests\AW.Services.SalesPerson.WCF.UnitTests\AW.Services.SalesPerson.WCF.UnitTests.csproj
          dotnet test src\Services\SalesPerson\tests\AW.Services.SalesPerson.WCF.UnitTests\AW.Services.SalesPerson.WCF.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
        
      - name: Build UI and run unit tests
        run: |
          dotnet build src\UI\tests\AW.UI.Web.Infrastructure.UnitTests\AW.UI.Web.Infrastructure.UnitTests.csproj --no-restore
          dotnet test src\UI\tests\AW.UI.Web.Infrastructure.UnitTests\AW.UI.Web.Infrastructure.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\UI\src\AW.UI.Web.Internal\AW.UI.Web.Internal.csproj --no-restore
          dotnet build src\UI\tests\AW.UI.Web.Internal.UnitTests\AW.UI.Web.Internal.UnitTests.csproj --no-restore
          dotnet test src\UI\tests\AW.UI.Web.Internal.UnitTests\AW.UI.Web.Internal.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
          dotnet build src\UI\src\AW.UI.Web.Store\AW.UI.Web.Store.csproj --no-restore
          dotnet build src\UI\tests\AW.UI.Web.Store.UnitTests\AW.UI.Web.Store.UnitTests.csproj --no-restore
          dotnet test src\UI\tests\AW.UI.Web.Store.UnitTests\AW.UI.Web.Store.UnitTests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}