name: customer-wcf

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-wcf.yml
  pull_request:
    branches: [ master ]
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-wcf.yml

jobs:
  BuildWindows:
    runs-on: windows-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Build and run unit tests
        run: |
          nuget restore src/AdventureWorks.sln
          cd src/Services/Customer

          dotnet build tests/AW.Services.Customer.Core.UnitTests/AW.Services.Customer.Core.UnitTests.csproj
          dotnet test tests/AW.Services.Customer.Core.UnitTests/AW.Services.Customer.Core.UnitTests.csproj --no-build --no-restore
          
          dotnet build tests/AW.Services.Customer.Infrastructure.EF6.UnitTests/AW.Services.Customer.Infrastructure.EF6.UnitTests.csproj
          dotnet test tests/AW.Services.Customer.Infrastructure.EF6.UnitTests/AW.Services.Customer.Infrastructure.EF6.UnitTests.csproj --no-build --no-restore

          msbuild.exe src/AW.Services.Customer.WCF/AW.Services.Customer.WCF.csproj /p:Platform=AnyCPU /p:Configuration=Release
          dotnet build tests/AW.Services.Customer.WCF.UnitTests/AW.Services.Customer.WCF.UnitTests.csproj
          dotnet test tests/AW.Services.Customer.WCF.UnitTests/AW.Services.Customer.WCF.UnitTests.csproj --no-build --no-restore
