name: customer-api

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-api.yml
  pull_request:
    branches: [ master ]    
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-api.yml

env:
  SERVICE: customer-api
  IMAGE: customer.api
  DOTNET_VERSION: 5.0.x

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: windows-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
     
      - name: Install Sonar global tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar scan
        run: dotnet sonarscanner begin /k:"ngruson_AdventureWorks" /d:sonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Build and run unit tests
        run: |
          cd src
          dotnet restore "AdventureWorks.sln"
          cd Services/Customer/AW.Services.Customer.REST.API
          dotnet build --no-restore
          cd -
          cd Services/Customer/AW.Services.Customer.REST.API.UnitTests
          dotnet build --no-restore
          dotnet test --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
