name: customer-wcf

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-wcf.yml

env:
  DOTNET_VERSION: 5.0.x

jobs:
  BuildWindows:
    runs-on: windows-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Restore Packages
        run: |
          cd src
          nuget restore AdventureWorks.sln

      - name: Build and run unit tests
        run: |
          cd src
          nuget restore AdventureWorks.sln
          cd Services/Customer/AW.Services.Customer.WCF
          msbuild.exe AW.Services.Customer.WCF.csproj /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
