name: customer-api

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-api.yml
  pull_request:
    branches: [ master ]
    paths:
    - src/Services/Customer/**
    - .github/workflows/customer-api.yml

env:
  SERVICE: customer-api
  IMAGE: customer.api
  DOTNET_VERSION: 6.0.x
  REGISTRY_NAME: cradventureworks
  APP_NAME: adventureworks_customerapi

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
   
      - name: Build and run unit tests
        run: |
          cd src/Services/Customer

          dotnet build tests/AW.Services.Customer.Core.UnitTests/AW.Services.Customer.Core.UnitTests.csproj
          dotnet test tests/AW.Services.Customer.Core.UnitTests/AW.Services.Customer.Core.UnitTests.csproj --no-build --no-restore --verbosity normal
          
          dotnet build tests/AW.Services.Customer.Infrastructure.EFCore.UnitTests/AW.Services.Customer.Infrastructure.EFCore.UnitTests.csproj
          dotnet test tests/AW.Services.Customer.Infrastructure.EFCore.UnitTests/AW.Services.Customer.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore --verbosity normal
          
          dotnet build src/AW.Services.Customer.REST.API/AW.Services.Customer.REST.API.csproj
          dotnet build tests/AW.Services.Customer.REST.API.UnitTests/AW.Services.Customer.REST.API.UnitTests.csproj
          dotnet test tests/AW.Services.Customer.REST.API.UnitTests/AW.Services.Customer.REST.API.UnitTests.csproj --no-build --no-restore --verbosity normal

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build the Docker image      
        run: |
          cd src
          docker build -f Services/Customer/src/AW.Services.Customer.REST.API/Dockerfile -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest .

      - name: Push Image to Docker
        run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
