name: department-api-pull-request

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]    
    paths:
    - src/Services/HumanResources/**
    - .github/workflows/department-api.yml

env:
  DOTNET_VERSION: 7.0.x

jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and run unit tests
        run: |
          cd src/Services/HumanResources
          
          dotnet build tests/AW.Services.HumanResources.Core.UnitTests/AW.Services.HumanResources.Core.UnitTests.csproj
          dotnet test tests/AW.Services.HumanResources.Core.UnitTests/AW.Services.HumanResources.Core.UnitTests.csproj --no-build --no-restore
          
          dotnet build src/AW.Services.HumanResources.Department.REST.API/AW.Services.HumanResources.Department.REST.API.csproj