name: reference-data-api-pull-request

on:
  workflow_dispatch:  
  pull_request:
    branches: [ main ]    
    paths:
    - src/Services/ReferenceData/**
    - .github/workflows/reference-data-api.yml

env:
  DOTNET_VERSION: 7.0.x

jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and run unit tests
        run: |
          cd src/Services/ReferenceData
          
          dotnet build tests/AW.Services.ReferenceData.Core.UnitTests/AW.Services.ReferenceData.Core.UnitTests.csproj
          dotnet test tests/AW.Services.ReferenceData.Core.UnitTests/AW.Services.ReferenceData.Core.UnitTests.csproj --no-build --no-restore
          
          dotnet build tests/AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests/AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests.csproj
          dotnet test tests/AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests/AW.Services.ReferenceData.Infrastructure.EFCore.UnitTests.csproj --no-build --no-restore
          
          dotnet build src/AW.Services.ReferenceData.REST.API/AW.Services.ReferenceData.REST.API.csproj
          dotnet build tests/AW.Services.ReferenceData.REST.API.UnitTests/AW.Services.ReferenceData.REST.API.UnitTests.csproj
          dotnet test tests/AW.Services.ReferenceData.REST.API.UnitTests/AW.Services.ReferenceData.REST.API.UnitTests.csproj --no-build --no-restore