name: reference-data-api

on:
  workflow_dispatch:  
  push:
    branches: [ master ]
    paths:
    - src/Services/ReferenceData/**
    - .github/workflows/reference-data-api.yml
  pull_request:
    branches: [ master ]    
    paths:
    - src/Services/ReferenceData/**
    - .github/workflows/reference-data-api.yml

env:
  SERVICE: reference-data-api
  IMAGE: reference-data.api
  DOTNET_VERSION: 5.0.x

jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and run unit tests
        run: |
          cd src
          dotnet restore "AdventureWorks.sln"
          cd Services/ReferenceData/src/AW.Services.ReferenceData.REST.API
          dotnet build --no-restore
