name: ui-web-internal

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    paths:
    - src/UI/Internal/**
    - src/UI/Infrastructure/**
    - src/UI/SharedKernel/**
    - .github/workflows/ui-web-internal.yml

env:
  DOTNET_VERSION: 6.0.x

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
   
      - name: Build and run unit tests
        run: |
          cd src/UI

          dotnet build Infrastructure/tests/AW.UI.Web.Infrastructure.UnitTests/AW.UI.Web.Infrastructure.UnitTests.csproj
          dotnet test Infrastructure/tests/AW.UI.Web.Infrastructure.UnitTests/AW.UI.Web.Infrastructure.UnitTests.csproj --no-build --no-restore --verbosity normal

          dotnet build SharedKernel/tests/AW.UI.Web.SharedKernel.UnitTests/AW.UI.Web.SharedKernel.UnitTests.csproj
          dotnet test SharedKernel/tests/AW.UI.Web.SharedKernel.UnitTests/AW.UI.Web.SharedKernel.UnitTests.csproj --no-build --no-restore --verbosity normal
          
          dotnet build Internal/tests/AW.UI.Web.Internal.UnitTests/AW.UI.Web.Internal.UnitTests.csproj
          dotnet test Internal/tests/AW.UI.Web.Internal.UnitTests/AW.UI.Web.Internal.UnitTests.csproj --no-build --no-restore --verbosity normal