name: ui-web-store

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - src/UI/Store/**
    - src/UI/Infrastructure/**
    - src/UI/SharedKernel/**
    - .github/workflows/ui-web-store.yml

env:
  DOTNET_VERSION: 7.0.x
  REGISTRY_NAME: cradventureworks
  APP_NAME: adventureworks_mvc_store

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
   
      - name: Build and run unit tests
        run: |
          cd src/UI

          dotnet build Infrastructure/tests/AW.UI.Web.Infrastructure.UnitTests/AW.UI.Web.Infrastructure.UnitTests.csproj
          dotnet test Infrastructure/tests/AW.UI.Web.Infrastructure.UnitTests/AW.UI.Web.Infrastructure.UnitTests.csproj --no-build --no-restore --verbosity normal

          dotnet build SharedKernel/tests/AW.UI.Web.SharedKernel.UnitTests/AW.UI.Web.SharedKernel.UnitTests.csproj
          dotnet test SharedKernel/tests/AW.UI.Web.SharedKernel.UnitTests/AW.UI.Web.SharedKernel.UnitTests.csproj --no-build --no-restore --verbosity normal
          
          dotnet build Store/tests/AW.UI.Web.Store.UnitTests/AW.UI.Web.Store.UnitTests.csproj
          dotnet test Store/tests/AW.UI.Web.Store.UnitTests/AW.UI.Web.Store.UnitTests.csproj --no-build --no-restore --verbosity normal

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build the Docker image      
        run: |
          cd src
          docker build -f UI/Store/src/AW.UI.Web.Store/Dockerfile -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest .

      - name: Push Image to Docker
        run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest